import type { Metadata } from "next";
import { Building2, Check, ChevronRight, Coins, UserPlus, UsersRound } from "lucide-react";

export const metadata: Metadata = { title: "Settings" };

export default function SettingsPage() {
  return (
    <div className="mx-auto max-w-4xl">
      <div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#849087]">Workspace</p><h1 className="mt-2 text-[30px] font-semibold tracking-[-.045em] sm:text-4xl">Settings</h1><p className="mt-2 text-sm text-[#6d7971]">Manage the business details and access used across CRAK.</p></div>
      <section className="mt-7 rounded-2xl border border-[#dfe5df] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#eaf6ee] text-[#087a4f]"><Building2 size={18} /></span><div><h2 className="text-base font-bold">Business profile</h2><p className="mt-0.5 text-xs text-[#7b877f]">The identity shown across your workspace.</p></div></div><form className="mt-6 grid gap-5 sm:grid-cols-2"><label className="block text-xs font-bold">Business name<input defaultValue="Freetown Coffee Co." className="mt-2 h-11 w-full rounded-lg border border-[#d9e1da] px-3 text-sm font-normal outline-none focus:border-[#087a4f]" /></label><label className="block text-xs font-bold">Workspace slug<input defaultValue="freetown-coffee" className="mt-2 h-11 w-full rounded-lg border border-[#d9e1da] px-3 text-sm font-normal outline-none focus:border-[#087a4f]" /></label><label className="block text-xs font-bold">Base currency<select className="mt-2 h-11 w-full rounded-lg border border-[#d9e1da] bg-white px-3 text-sm font-normal"><option>SLE — Sierra Leonean Leone</option><option>USD — US Dollar</option></select></label><div className="flex items-end"><button type="button" className="inline-flex h-11 items-center gap-2 rounded-lg bg-[#087a4f] px-4 text-xs font-bold text-white"><Check size={15} /> Save changes</button></div></form></section>
      <section className="mt-4 rounded-2xl border border-[#dfe5df] bg-white p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><span className="grid size-10 place-items-center rounded-xl bg-[#fff0e3] text-[#a65f27]"><Coins size={18} /></span><div className="flex-1"><h2 className="text-base font-bold">Wallet provisioning</h2><p className="mt-1 text-xs text-[#7b877f]">Your financial account is ready to accept funding.</p></div><span className="w-fit rounded-full bg-[#eaf6ee] px-3 py-1.5 text-[10px] font-bold text-[#087a4f]">Active</span></div></section>
      <section className="mt-4 overflow-hidden rounded-2xl border border-[#dfe5df] bg-white"><div className="flex items-center justify-between border-b border-[#e5eae6] px-5 py-4 sm:px-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#f1ecff] text-[#6954a4]"><UsersRound size={18} /></span><div><h2 className="text-base font-bold">Team access</h2><p className="mt-0.5 text-xs text-[#7b877f]">Give teammates the least access they need.</p></div></div><button className="inline-flex h-9 items-center gap-2 rounded-lg border border-[#d9e1db] px-3 text-xs font-bold"><UserPlus size={15} /> <span className="hidden sm:inline">Add member</span></button></div>{[{ name: "Mohamed Kamara", email: "mohamed@freetowncoffee.sl", role: "Owner", initials: "MK" }, { name: "Hannah Cole", email: "hannah@freetowncoffee.sl", role: "Admin", initials: "HC" }].map((member) => <button key={member.email} className="flex w-full items-center gap-3 border-b border-[#edf0ed] px-5 py-4 text-left last:border-0 sm:px-6"><span className="grid size-9 place-items-center rounded-full bg-[#edf3ee] text-[10px] font-bold">{member.initials}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-bold">{member.name}</span><span className="mt-1 block truncate text-[10px] text-[#849087]">{member.email}</span></span><span className="rounded-full bg-[#f1f4f1] px-2.5 py-1 text-[10px] font-bold text-[#66736b]">{member.role}</span><ChevronRight size={15} className="text-[#8e9891]" /></button>)}</section>
    </div>
  );
}
